spring.application.name=prepgenius-backend

spring.config.import=optional:file:.env[.properties]

spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/prepgenius}

jwt.secret=${JWT_SECRET:024aQBoy46vOjN7UNZjgvuNOZ7RYsuzEgUUWKPcF648ug8njbekSjKMYjDqi/INXh8bC9+6SV8MjHfJ+vS05VA==}
jwt.expiration=86400000

frontend.url=${FRONTEND_URL:http://localhost:5173}

admin.default.email=${ADMIN_EMAIL:admin@prepgenius.com}
admin.default.password=${ADMIN_PASSWORD:Admin@123}
admin.default.name=${ADMIN_NAME:PrepGenius Admin}

gemini.api.key=${GEMINI_API_KEY:}
gemini.model=${GEMINI_MODEL:gemini-1.5-flash}
gemini.base-url=${GEMINI_BASE_URL:https://generativelanguage.googleapis.com/v1beta/models/}
gemini.timeout-seconds=${GEMINI_TIMEOUT_SECONDS:60}

server.port=8080

logging.level.org.springframework.data.mongodb=INFO
logging.level.org.springframework.security=INFO
